version: '3'
services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    command: 'mitmweb --web-iface 0.0.0.0'
    volumes:
      - mitmvol://home/mitmproxy/.mitmproxy
    ports:
      - 8081:8081

  azurecli:
    image: microsoft/azure-cli
    stdin_open: true
    tty: true
    environment: 
      HTTPS_PROXY: https://mitmproxy:8080
      AZURE_CLI_DISABLE_CONNECTION_VERIFICATION: 'true'

volumes:
  mitmvol: